[tool.poetry]
name = "secret-santa-pp"
version = "1.0.0"
description = "Secret santa with a few extra bells and whistles"
authors = ["Joe Jacobs <git@hazardcell.com>"]
readme = "README.md"
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
matplotlib = "*"
networkx = "*"
pydantic = {version = "*", extras = ["email"]}
python = "^3.12"
rich = "*"
scipy = "*"
typer = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "*"

[tool.ruff]
exclude = [
    ".coverage",
    ".git",
    ".pytest_cache",
    ".ruff_cache",
]
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
