[tool.poetry]
name = "SecretSanta++"
version = "1.0.0"
description = "Secret santa with a few extra bells and whistles"
authors = ["Joe Jacobs <git@hazardcell.com>"]
readme = "README.md"
license = "AGPL-3.0-or-later"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.9.0"
rich = "^13.7.1"
networkx = "^3.2.1"
matplotlib = "^3.8.3"
scipy = "^1.12.0"
pydantic = {version = "^2.6.4", extras = ["email"]}

[tool.poetry.group.test.dependencies]
pytest = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
