version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    executor: python.default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest
workflows:
  example:
    jobs:
      - test
