version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
  python: circleci/python@2.1.1
jobs:
  test:
    executor:
      name: python/default
      tag: '3.12'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test
      - run:
          name: Upload test coverage to codecov
          command: codecov/upload
workflows:
  build_and_test:
    jobs:
      - test
