version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    executor:
      name: python/default
      tag: '3.12'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test
      - store_artifacts:
          path: htmlcov
workflows:
  build_and_test:
    jobs:
      - test
